{
 "title": "slrp",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Proxy count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slrp_pool_proxy_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "avg success rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slrp_avg_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sampled success rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slrp_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "beta sample",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slrp_beta_sample", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sampled success rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "slrp_success_rate", "legendFormat": "__auto" },
    { "expr": "slrp_avg_success_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proxy count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "slrp_pool_proxy_total", "legendFormat": "__auto" }
   ]
  }
 ]
}